import type { Metadata } from "next";
import { Montserrat, Lato } from "next/font/google";
import { ApolloWrapper } from "@/app/ApolloWrapper";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const montserrat = Montserrat({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-montserrat",
});

const lato = Lato({
    subsets: ["latin"],
    weight: ["100", "300", "400", "700", "900"],
    variable: "--font-lato",
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${montserrat.variable} ${lato.variable}`}>
                <Header />
                <ApolloWrapper>
                    <main>{children}</main>
                </ApolloWrapper>
                <Footer />
            </body>
        </html>
    );
}
