import type { Metadata } from "next";
import { Montserrat, Lato } from "next/font/google";
import { ApolloWrapper } from "@/app/ApolloWrapper";
import "./globals.css";
import Header from "@/components/Layout/Header/Header";
import Footer from "@/components/Layout/Footer/Footer";
import Image from "next/image";
import logo from "@/assets/images/logo-header.png";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const montserrat = Montserrat({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-montserrat",
});

const lato = Lato({
    subsets: ["latin"],
    weight: ["100", "300", "400", "700", "900"],
    variable: "--font-lato",
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${montserrat.variable} ${lato.variable}`}>
                <Header />
                <ApolloWrapper>
                    <main>{children}</main>
                </ApolloWrapper>
                <Footer />
                <div className="width-limit">
                    <Image src={logo} alt="" className="m-auto mt-12" />
                    <h1 className="text-center text-2xl mt-5 text-gr-green font-lato w-3/4 m-auto font-semibold">
                        We apologize the site is not responsive, the minimum
                        viewing width is 1050 pixels
                    </h1>
                </div>
            </body>
        </html>
    );
}
